실제 효과가 있을까?

In [45]:
from tensorflow.keras.models import *
import pickle
from konlpy.tag import Okt, Mecab
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

#모델 로드
# model = load_model('model/gender_classfication_0.7880811095237732.h5')
model = load_model('model/gender_classfication_0.763458788394928_kkma.h5')
# model = load_model('model/gender_classfication_0.7989316582679749_mecab.h5')

with open('model/gender_token_kkma.pickle', 'rb') as f :
  token = pickle.load(f)

# with open('model/gender_token_mecab.pickle', 'rb') as f :
#   token = pickle.load(f)
  
with open('model/gender_encoder.pickle', 'rb') as f:
  encoder = pickle.load(f)
category = encoder.classes_
print (category)

[1 2 3]


In [1]:
from konlpy.tag import Mecab
mecab=Mecab(dicpath='C:/mecab/mecab-ko-dic')
mecab.morphs('아 더빙 진짜 짜증 나네요 목소리')

# 형태소 단위 : mecab.morphs()
# 명사 단위    : mecab.nouns()
# 품사 태깅    : mecab.pos()

['아', '더', '빙', '진짜', '짜증', '나', '네요', '목소리']

In [19]:
X = ['은지','민지','민준','가영','지원','마다가스카','졸라맨']
okt = Okt()
print(type(X))
okt_X = okt.morphs(X[1])
print(X[1])
print(okt_X)

for i in range(len(X)):
  X[i] = okt.morphs(X[i])
print(X)

<class 'list'>
민지
['민지']
[['은지'], ['민지'], ['민준'], ['가', '영'], ['지원'], ['마다가스카'], ['졸라맨']]


In [47]:
from konlpy.tag import Kkma
X = ['리자', '미자', '행자', '춘향', '화자', '채주', '채진', '가람','하랑','하람','하온']
# X = ['은지','민지','민준','가영','지원','마다가스카','가나다라']
kkma = Kkma()
print(type(X))
kkma_X = kkma.morphs(X[1])
print(X[1])
print(kkma_X)

for i in range(len(X)):
  X[i] = kkma.morphs(X[i])
print(X)

<class 'list'>
미자
['미', '자']
[['리', '자'], ['미', '자'], ['행자'], ['추', 'ㄴ', '향'], ['화자'], ['채주'], ['채', '진'], ['가람'], ['하', '랑'], ['하', '람'], ['하', '온']]


In [36]:
X = ['은지','민지','민준','가영','지원','마다가스카','가나다라']

mecab=Mecab(dicpath='C:/mecab/mecab-ko-dic')
print(type(X))
mecab_X = mecab.morphs(X[1])
print(X[1])
print(mecab_X)

for i in range(len(X)):
  X[i] = mecab.morphs(X[i])
print(X)

<class 'list'>
민지
['민지']
[['은지'], ['민지'], ['민준'], ['가영'], ['지원'], ['마다가스카'], ['가나다', '라']]


In [37]:
X = ['리자', '미자', '행자', '춘향', '화자', '채주', '채진', '가람','하랑','하람','하온']
mecab=Mecab(dicpath='C:/mecab/mecab-ko-dic')
print(type(X))
mecab_X = mecab.morphs(X[1])
print(X[1])
print(mecab_X)

for i in range(len(X)):
  X[i] = mecab.morphs(X[i])
print(X)

<class 'list'>
미자
['미자']
[['리자'], ['미자'], ['행자'], ['춘향'], ['화자'], ['채주'], ['채진'], ['가람'], ['하랑'], ['하람'], ['하', '온']]


In [48]:
tokened_X = token.texts_to_sequences(X)
# print(tokened_X[0])

X_pad = pad_sequences(tokened_X, 14)
# print(X_pad[:10])

predict = model.predict(X_pad)
for i in range(len(X)) :
    print(predict[i])

result = np.argmax(predict[4])
# print(category[result])


# 지원의 경우 남자 : 여자 = 4 : 6 비율인데 너무 높게 평가함
# kkma 0.77 / mecab 0.65

# X = ['리자', '미자', '행자', '춘향', '화자', '채주', '채진', '가람','하랑','하람','하온']


[0.015673   0.98222995 0.00209707]
[0.02595359 0.97191894 0.00212749]
[0.08206727 0.82945734 0.08847538]
[0.03708567 0.954908   0.00800628]
[0.45388478 0.3897056  0.1564096 ]
[0.40891418 0.41157192 0.17951393]
[0.2636865  0.6670584  0.06925506]
[0.5184662  0.3555434  0.12599047]
[0.2853556  0.6219586  0.09268581]
[0.67864215 0.22956985 0.09178805]
[0.62387043 0.27893582 0.09719376]


In [49]:
predict_gender = []
for pred in predict :
  predict_gender.append(category[np.argmax(pred)])
print(predict_gender)

#X = ['리자', '미자', '행자', '춘향', '화자', '채주', '채진', '가람','하랑','하람','하온']


[2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1]
